title: Daniel Ruth # your name (or website title) here
logo: "/images/photo_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Ph.D. Candidate in Mechanical and Aerospace Engineering at Princeton University
  <br><br>
  fluid mechanics | multiphase flows | turbulence | experimental methods
  <br><br>
  <a href="https://scholar.google.com/citations?user=ofp5PZcAAAAJ&hl=en">Google Scholar</a>
  <br>
  <a href="https://www.linkedin.com/in/danielruth/">LinkedIn</a>
  <br>
  <a href="https://github.com/danjruth">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
github:
  is_project_page: false
